account/urls.py
from django.urls import path
from django.contrib.auth import views as django_auth_views

from account.views import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', django_auth_views.logout_then_login, name='logout'),
]

location/urls.py
from django.urls import path

from location.views import (
    CountryCreateView,
    AdministrativeRegionCreateView,
    GeographicRegionCreateView,
    MarkOfQualityCreateView,
    PackageCreateView,
    LoadLocations
)

app_name = 'location'

urlpatterns = [
    path('country/create/', CountryCreateView.as_view(), name='country-create'),
    path('administrative/region/create/',
         AdministrativeRegionCreateView.as_view(),
         name='administrative-region-create'),
    path('geographic/region/create/', GeographicRegionCreateView.as_view(),
         name='geographic-region-create'),
    path('mark/quality/create/', MarkOfQualityCreateView.as_view(),
         name='mark-quality-create'),
    path('package/create/', PackageCreateView.as_view(),
         name='package_create'),
    path('load/location/', LoadLocations.as_view(),
         name='ajax_load_locations'),
]

test_task/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='login', permanent=False)),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
    path('locations/', include('location.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Locations</title>


    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>

<body id="base">


{% include 'navbar.html' %}


<div class="container" id="base_container">
    {% block content %}{% endblock content %}
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"
        integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base_location.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Locations</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>

{% include 'navbar.html' %}

{% block location %}

{% endblock location %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff %}
                        <a class="nav-link" href="{% url 'admin:index' %}">{{ request.user.username }} <span
                                class="sr-only"></span></a>
                    {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Possible actions
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'location:country-create' %}">Create country</a>
                    <a class="dropdown-item" href="{% url 'location:geographic-region-create' %}">Create geographic
                        region</a>
                    <a class="dropdown-item" href="{% url 'location:administrative-region-create' %}">Create
                        administrative region</a>
                    <a class="dropdown-item" href="{% url 'location:mark-quality-create' %}">Create mark of quality</a>
                    <a class="dropdown-item" href="{% url 'location:package_create' %}">Create package</a>
                </div>
            </li>
        </ul>
    </div>
</nav>